### ISSUE TITLE
现在这个demo还维护吗？

### ISSUE THREAD

**Issue by ufofly** [chronolaw/http_study#1]
弄了一天也无法成功，只有Nginx的界面，没有网站的界面。openresty版本也换了很多个，都无法成功

**Comment by chronolaw** [comment]
这个主要是用来研究http协议，对浏览器不是太看重。

代码、配置都是测试过的没有问题，可以照着课程搭建，也可以用docker搭建，在外部用浏览器。

**Comment by ufofly** [comment]
老师可以用最新的版本测试一下吗？

**Comment by ufofly** [comment]
2021/04/16 15:06:59 [emerg] 2060#9612: bind() to 0.0.0.0:443 failed (10013: An attempt was made to access a socket in a way forbidden by its access permissions)
解决不了这个报错，老师可以帮忙看一下吗？
