### ISSUE TITLE
http 500

### ISSUE THREAD

**Issue by heqishengcai** [chronolaw/http_study#3]
你好，本地mac系统编译的openresty，但是部分lua脚本报错。

2021/05/21 12:52:15 [error] 31008#0: *79 lua entry thread aborted: runtime error: /opt/webroot/openresty_demo/http_study/www/lua/19-1.lua:3: module 'ngx.resp' not found:
	no field package.preload['ngx.resp']
	no file '/opt/webroot/openresty_demo/http_study/www//lua/ngx/resp.lua'
	no file '/usr/local/openresty/lualib/ngx/resp.lua'
	no file '/usr/local/openresty/lualib/ngx/resp/init.lua'
	no file './ngx/resp.lua'
	no file '/usr/local/openresty/luajit/share/luajit-2.1.0-beta1/ngx/resp.lua'
	no file '/usr/local/share/lua/5.1/ngx/resp.lua'
	no file '/usr/local/share/lua/5.1/ngx/resp/init.lua'
	no file '/usr/local/openresty/luajit/share/lua/5.1/ngx/resp.lua'
	no file '/usr/local/openresty/luajit/share/lua/5.1/ngx/resp/init.lua'
	no file '/opt/webroot/openresty_demo/http_study/www//lua/lib/ngx/resp.so'
	no file '/usr/local/openresty/lualib/ngx/resp.so'
	no file './ngx/resp.so'
	no file '/usr/local/lib/lua/5.1/ngx/resp.so'
	no file '/usr/local/openresty/luajit/lib/lua/5.1/ngx/resp.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file '/opt/webroot/openresty_demo/http_study/www//lua/lib/ngx.so'
	no file '/usr/local/openresty/lualib/ngx.so'
	no file './ngx.so'
	no file '/usr/local/lib/lua/5.1/ngx.so'
	no file '/usr/local/openresty/luajit/lib/lua/5.1/ngx.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
coroutine 0:
	[C]: in function 'require'

-----------

2021/05/21 12:33:22 [error] 31008#0: *74 lua entry thread aborted: runtime error: /opt/webroot/openresty_demo/http_study/www/lua/17-1.lua:10: expecting 3 arguments, but only seen 5
stack traceback:
coroutine 0:
	[C]: in function 'incr'

**Comment by heqishengcai** [comment]
restry.conf 中的这个prefix变量指的是？
lua_package_path    "$prefix/lua/?.lua;;";
lua_package_cpath   "$prefix/lua/lib/?.so;;";

**Comment by chronolaw** [comment]
ngx.resp是lua-resy-core库的，可能是自编译的没有安装，最好下载打包好的，保证程序齐全。
看ngx lua的文档，就是nginx启动时的-p目录。

**Comment by Apocaly-pse** [comment]
老师,我替换了您说的这三个部分(源码), 并在M1的Mac上成功编译了, 但是还是会显示500的服务器错误, 日志仍显示上面的lua错误, 是不是目前没办法在M1的mac上成功运行呢?
