### ISSUE TITLE
访问具体资源返回500

### ISSUE THREAD

**Issue by doubleLLL3** [chronolaw/http_study#4]
老师您好，我访问大多数具体资源，如`http://127.0.0.1/09-1`时，返回500，这个问题该怎么查呢？从lua入手吗？
<img width="1872" alt="image" src="https://user-images.githubusercontent.com/44157339/180641673-d27d53fc-cf25-4a77-aff6-0dbb5bb11477.png">

捞了下日志（logs/http_access.log）看到下面的信息：
> 127.0.0.1 - - [24/Jul/2022:17:46:04 +0800] "GET /09-1 HTTP/1.1" 500 585 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36" "-"

还有哪些线索呢？

---
环境：Mac M1

<img width="200" alt="image" src="https://user-images.githubusercontent.com/44157339/180641692-12fa340b-5142-4302-a664-2830f1159284.png">

**Comment by chronolaw** [comment]
应该看error.log，里面会有详细的错误信息，看access.log不能帮助排错。

**Comment by doubleLLL3** [comment]
> 2022/07/24 21:34:09 [error] 123#4370202: *3 lua entry thread aborted: runtime error: ...llar/openresty/1.21.4.1_1/lualib/resty/core/response.lua:102: NYI: cannot call this C function (yet)
stack traceback:
coroutine 0:
	[C]: in function 'ngx_http_lua_ffi_set_resp_header'
	...llar/openresty/1.21.4.1_1/lualib/resty/core/response.lua:102: in function '__newindex'
	/Users/double/Projects/http_study/www/lua/09-1.lua:34: in main chunk, client: 127.0.0.1, server: localhost, request: "GET /09-1 HTTP/1.1", host: "127.0.0.1"


找到了老师的这个修复👍：https://github.com/openresty/lua-resty-core/commit/da705fcaaf85f351fa87480816b4f41a65fc4bd5

看起来需要自己编译一下？

**Comment by chronolaw** [comment]
哦，原来是在m1芯片上运行的啊，现在这个补丁还没正式发布，只能自己编译OpenResty了。

**Comment by doubleLLL3** [comment]
老师有合适的编译教程吗？自己找了一圈，没找到合适的，编译小白~

**Comment by chronolaw** [comment]
这个最好自己下载源码编译，替换一下OpenResty包里的ngx_lua、stream_lua、lua-resty-core就行了。

**Comment by chronolaw** [comment]
> 老师有合适的编译教程吗？自己找了一圈，没找到合适的，编译小白~

替换后执行./configure，然后make & make install。

**Comment by doubleLLL3** [comment]
谢谢老师，我去试试～

**Comment by Apocaly-pse** [comment]
老师,我替换了您说的这三个部分(源码), 并在M1的Mac上成功编译了, 但是还是会显示500的服务器错误, 日志仍显示上面的lua错误, 是不是目前没办法在M1的mac上成功运行呢?

**Comment by chronolaw** [comment]
我很少直接在Mac上工作，都是用的虚拟机再安装Linux。

因为M1芯片目前的支持还不完善，有可能有这样的问题，建议用虚拟机的Linux环境最好。

**Comment by Apocaly-pse** [comment]
> 我很少直接在Mac上工作，都是用的虚拟机再安装Linux。
> 
> 因为M1芯片目前的支持还不完善，有可能有这样的问题，建议用虚拟机的Linux环境最好。

是的, 我在x86_64的Ubuntu就可以跑了, 谢谢老师.
